### ISSUE TITLE
Exposed Key in .env.local File

### ISSUE THREAD

**Issue by edem-cyber** [tryVital/quickstart#4]
Issue Description: Exposed NEXT_PUBLIC_VITAL_API_KEY in .env.local File

Current State:

The exposed key exists within the .env.local file and has been committed to the repository's history.
This key is accessible to anyone with access to the repository.

<img width="339" alt="Screenshot 2023-12-19 at 23 54 33" src="https://github.com/tryVital/quickstart/assets/51761485/197dc62c-5d20-4413-a4d7-77afa373637e">

**Comment by maitham** [comment]
Thanks for this! Was a throw away key!
